export const SET_SETTINGS = 'SET_SETTINGS';
export const UPDATE_SETTING = 'UPDATE_SETTING';
export const ADD_NOTICE = 'ADD_NOTICE';
export const DELETE_NOTICE = 'DELETE_NOTICE';
export const SET_TOTAL_NOTIFICATIONS = 'SET_TOTAL_NOTIFICATIONS';
export const TOGGLE_PRO_ALERT = 'TOGGLE_PRO_ALERT';
export const TOGGLE_MERGE_TAGS = 'TOGGLE_MERGE_TAGS';
